name: DevOps test pipeline
on: [push]
jobs:
  Unit-Test-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      # - run: pip install -r requirements-dev.txt
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"
      - run: python -m unittest tests/unit_test_app.py


#COULD NOT RUN THE INTEGRATION AND E2E TEST BECAUSE THE APP IS NOT DEPLOYED
 # Integration-Test-Actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - uses: actions/setup-python@v3
  #       with:
  #         python-version: '3.9'
  #         cache: 'pip'
  #     # - run: pip install -r requirements-dev.txt
  #     - name: Install Python dependencies
  #       uses: py-actions/py-dependency-install@v3
  #       with:
  #         path: "requirements.txt"
  #     - run: python main.py &
  #     - run: pytest -v

  BuildDockerImage:
    runs-on: ubuntu-latest
    needs: 
      - Unit-Test-Actions
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-app:${{ github.sha }}

